[build]
  command = "CI=false npm run build"
  publish = "build"         

[[redirects]]
  from = "/api/*"
  to = "https://dony-shop-c2563d3d31e6.herokuapp.com/api/:splat"
  status = 200
  force = true
